[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[build.environment]
  SHARP_IGNORE_GLOBAL_LIBVIPS="true"

[build]
  publish = "public/"
  command = "head -n 2 ../contents.json && yarn run build"
