name: Ruby

on:
  push:
    branches: [ ga ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Build and test with Rake
      run: |
        gem install awesome_bot
        awesome_bot check-unique.txt --allow-ssl -a 302 -w xbmc/xbmc
        awesome_bot check-links.txt  --allow-ssl -a 403 --allow-dupe
        awesome_bot check-info.txt -a 403
